name: publish

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install requirements
      run: |
        pip install --upgrade build
        pip install --upgrade setuptools wheel setuptools-scm[toml]
        pip list

    - name: Package distribution
      run: |
        python -m build

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      continue-on-error: true
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository-url: https://test.pypi.org/legacy/
        verbose: true
        skip-existing: true

    - name: Publish distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        verbose: true
